apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artikos

resources:
- ../../base
- resources/ingress.yaml
images:
- name: artikos-integration
  newName: acrzscleus2.azurecr.io/artikos-integration
  newTag: 1.0.0

generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- patch/resourceLimits.yaml
- patch/replicas.yaml
- patch/envvars.yaml
- patch/affinity.yaml
