apiVersion: v1  # Versión de la API que se está utilizando para el Service
kind: Service  # Tipo de objeto que se está creando, en este caso un Service
metadata:
  name: artikos-integration # Nombre del Service
  labels:
    app: artikos-integration # Etiqueta para identificar la aplicación
    tier: artikos  # Etiqueta para identificar el proyecto o capa
spec:
  ports:
  - port: 80  # Puerto en el que el Service estará disponible
    protocol: TCP  # Protocolo utilizado en el puerto
    targetPort: 8080  # Puerto en el que el contenedor está escuchando (se puede usar el nombre del puerto por ejemplo: http)
  selector:
    app: artikos-integration # Selector que coincide con las etiquetas de los Pods
    tier: artikos  # Selector que coincide con las etiquetas de los Pods
  sessionAffinity: None  # Afinidad de sesión: ninguna, las solicitudes no se fijan a un Pod específico
  type: ClusterIP  # Tipo de Service: accesible solo dentro del clúster
